version: "3"
services: 
  zookeeper:
    image: zookeeper
    restart: always
    ports: 
      - 2181:2181
    container_name: "tap-zookeeper"
    networks: 
      - tap

networks: 
  tap:
    driver: bridge
    
